# Connect to the server docker
version: "3.8"
services:
  conduitdomain:
    build:
      context: "./server"
    ports:
      - "3001:3001"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
