# Connect to the server docker
version: "3.8"
services:
  conduitserver:
    build:
      context: "./server"
    ports:
      - "3001:3001"
  conduitclient:
    build:
      context: "./client"
    ports:
      - "3000:3000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
